version: '3'
volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      # device: '/home/$USER/inception/data/wordpress'
      device: '/Users/$USER/inception/data/wordpress'
  md:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      # device: '/home/$USER/inception/data/mariadb'
      device: '/Users/$USER/inception/data/mariadb'

networks:
  inception:

services:
  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - md:/var/lib/mysql
    networks:
      inception:
    env_file: .env
    restart: unless-stopped

  nginx:
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      inception:
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      inception:
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb


